[package]
name = "forecast"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
serde_json = "1"
config = { path = "../config" }
events = { path = "../events" }
scheduler = { path = "../scheduler" }
state = { path = "../state" }
